name: Go

on:
  push:
    branches: [ improving_coverage ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

#      - name: Check commit messages
#        uses: wagoid/commitlint-github-action@v4

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: |
          go build -v ./...

      - name: Test
        run: |
          export PORT=6790
          curl --silent --location "https://github.com/keploy/keploy/releases/latest/download/keploy_linux_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/keploy /usr/local/bin && export KEPLOY_MODE=off && keploy &
          export PORT=6789 && export ENABLE_TEST_EXPORT=false && go test -coverpkg=./... -coverprofile=coverage.tmp.txt -covermode=atomic ./...
          cat coverage.tmp.txt | grep -v -e "http/regression/request.go" | grep -v -e "generated.go" -e "_gen.go" | grep -v -e "services.pb.go" -e "services_grpc.pb.go" > coverage.txt
        env:
          ENABLE_DEDUP: true
          ENABLE_TELEMETRY: false



      #       - uses: codecov/codecov-action@v2
      #         with:
      #           files: ./coverage.txt
      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest
      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=coverage.txt -service=github

# #      - name: Install extra dependencies
# #        run: npm install -g @semantic-release/exec
#       - uses: codfish/semantic-release-action@additional-packages
#         with:
#           additional_packages: |
#             ['@semantic-release/exec']
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
